version: "3.7" # Version de python
services: # abajo coloco la app
    app: # creo contenedor app
        depends_on: # depende de mysql
            - "mysql"
        container_name: #  nombre del contenedor
            - flask-rest-mysql-app
        build:
            context: ./ #construye a partir de esta ruta
            dockerfile: dockerfile # el dockerfile que arme antes
        image:
            - flask-rest-mysql-app:latest # nombre de la imagen
        enviroment:
            FLASK_ENV: development
            DB_USUARIO: root
            DB_CLAVE: rodrigodatabase
            DB_HOST: mysql
            DB_NOMBRE: db_api_python
            JWT_SECRET_KEY: 3st4-3s-M1-Cl4ave-Se3cr3ta
        ports:
            - "5000:5000"
        restart: always # si hay algun error con el servicio si la app dejo de funcionar que la reinicie siempre
        networks:
            - internal
    mysql: # creo contenedor mysql
        container_name: mysql
        image: mysql:8.0
        restart: always
        enviroment:
            - MYSQL_ROOT_PASSWORD=rodrigodatabase
            - MYSQL_DATABASE=db_api_python
        ports:
            - "3306:3306"
        networks:
            - internal
networks:
    internal:
        driver: bridge
    